language: node_js
sudo: required
dist: trusty
node_js: stable
before_script:
- npm install -g bower polylint web-component-tester
- bower install
addons:
  firefox: '46.0'
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
  sauce_connect: true
script:
- polylint
- xvfb-run wct
cache:
  directories:
  - bower_components
